### ISSUE TITLE
Mark character color, how get it working? 

### ISSUE THREAD

**Issue by ReneFroger** [rhysd/clever-f.vim#19]
Thanks for sharing this awesome plugin! How does `g:clever_f_mark_char_color` work? I found no example by yet. 

For example, when I do: `g:clever_f_mark_char_color="Statement"` 

And in my colorscheme the Statement is defined as:

`hi Statement                  guifg=#8a3824    guibg=NONE        guisp=NONE         gui=bold`

But I see no another colors of the matching character when I press f{insert character} ?

**Comment by aliveupstairs** [comment]
any updates?

**Comment by rhysd** [comment]
At least on my laptop above config I showed works fine with both GUI version and CUI version. What I can say is,

```
hi Statement                  guifg=#8a3824    guibg=NONE        guisp=NONE         gui=bold
```

this color definition only defines colors for GUI version. It does not make any color on CUI version.

**Comment by emr-arvig** [comment]
This worked for me

Had to put _after_ colorscheme 

```
highlight CustomH ctermfg=white ctermbg=NONE cterm=bold,underline guifg=white guibg=NONE gui=bold,underline
highlight link CleverFChar CustomH
```

I am not sure why the highlight link is not working when there is an obvious if statement that should do it, but for whatever reason this is what I had to do.

**Comment by BertrandSim** [comment]
Changing the `:colorscheme` resets all highlights to their defaults (including those specified with `:hi link`). That is why the custom highlighting commands have to go after `:colorscheme`. This can be mitigated with an autocommand, eg.
```
function! Highlight-clever-f()
    highlight CustomH ctermfg=white ctermbg=NONE cterm=bold,underline guifg=white guibg=NONE gui=bold,underline
    highlight link CleverFChar CustomH
endfunction

call Highlight-clever-f()
autocmd Colorscheme * call Highlight-clever-f() 
```

Regarding the setting of  
```
let g:clever_f_mark_char = 1
let g:clever_f_mark_char_color = "Statement"
```
The highlights will be cleared after a change in colorscheme. This should be fixed in the plugin itself... let me issue a patch for this
