### ISSUE TITLE
mapping `clever-f-reset` doesn't work

### ISSUE THREAD

**Issue by hoschi** [rhysd/clever-f.vim#23]
or I'm too dumb to get it right ... ^^

I tried as normal with:

```
nm <Leader>f          <Plug>(clever-f-reset)
```

with `,` as leader. When I do this `f` doesn't work anymore. Ther cursor jumps to the status line when I press `f` and return to previous position when I press another key to search for that character. But it doesn't search any more :(

**Comment by zlksnk** [comment]
@hoschi have you got it working?

**Comment by rhysd** [comment]
Can you show exact steps? I tried the mapping and it worked as expected in my side

**Comment by hoschi** [comment]
Hm. `f` works now, with the mapping installed.

However, `,f` doesn't seem to reset "clever f". When I start searching by `fn` for char "n" I see highlights for every "n". My use case is that I want to search for another character, but pressing `,f` still searches for "n".

**Comment by rhysd** [comment]
Thanks for the comment. I'm reopening this and will look into it.

**Comment by rhysd** [comment]
I tried the following steps but it did not reproduce this issue. Could you try the same?

1. Save the following `vimrc` file in current directory
2. Open Vim with `vim -N -u ./vimrc`
3. Search some character for example `faff`
4. Type `,f`
5. Type `fb` and check if 'b' is searched with this plugin

```vim
set nocompatible

set rtp+=~/.vim/bundle/clever-f.vim

let mapleader = ','

nmap <Leader>f <Plug>(clever-f-reset)
```

**Comment by hoschi** [comment]
That actually works! I guess I need then to find the problem in my (not so small) config 🙃.

**Comment by rhysd** [comment]
I recommend to check `:nmap <Leader>f` in your Vim.

**Comment by hoschi** [comment]
I checked that first, it shows only the binding to clever-f

**Comment by rhysd** [comment]
> That actually works! I guess I need then to find the problem in my (not so small) config 🙃.

If you find this issue is a problem of this plugin, please let me know by leaving a comment. Closing this issue meanwhile.
