### ISSUE TITLE
Clever-f jumps to wrong characters

### ISSUE THREAD

**Issue by kyouryuukunn** [rhysd/clever-f.vim#24]
Clever-f jumps to wrong characters, If clever-f set like below.
let g:clever_f_ignore_case = 1
let g:clever_f_use_migemo = 1
let g:clever_f_across_no_line = 0

Then, typing "fs" jumps to not only "s" but also "o"
![test](https://cloud.githubusercontent.com/assets/1556311/6818076/112cd410-d2ed-11e4-94bf-ebc4f49e367d.gif)

**Comment by rhysd** [comment]
I'm replying in Japanese because you're using migemo feature.

報告ありがとうございます．
手元で試してみた限りでは正しく `S` だけにマッチするのですが，そのスクリーンショットの `SOS` はもしかして全角だったりしますか？

**Comment by kyouryuukunn** [comment]
いえ、半角英数です。

**Comment by rhysd** [comment]
勘違いしてました，`across_no_line = 0` なんですね．失礼しました．

`across_no_line = 0` のときに `use_migemo = 1` とすると常に入力の文字に対して `migemo` から生成された辞書が使われます．
具体的な辞書定義は[これ](https://github.com/rhysd/clever-f.vim/blob/master/autoload/clever_f/migemo/utf8.vim#L21)です．
そして，どうやら `migemo` のマッチングは入力文字数が少ないときはあまり精度が良くないらしく，`O` も入力 `s` に対してマッチしてしまうようです…

申し訳ないのですが，これはこちらではどうすることもできないので仕様です．`across_no_line = 1` とすると現在行にマルチバイト文字があるかどうかを見て普通に1文字マッチさせるか辞書を使った migemo マッチをさせるかを自動選択するため期待動作になります．

うーん，一応対策としては，`across_no_line = 1` でも現在行だけみて辞書を使うかどうかを切り替えるオプションを追加するぐらいしか思いつかないです．（バッファ全体を走査してマルチバイト文字があるかどうかを判定すれば可能ですが，パフォーマンス的に厳しくなるので難しいです）

**Comment by kyouryuukunn** [comment]
了解です。

**Comment by rhysd** [comment]
@kyouryuukunn 

なんとかなりそうなので reopen しました．

**Comment by rhysd** [comment]
@kyouryuukunn 

入力した文字と矛盾する半角文字にヒットしないように手を入れてみました．手元では期待通りに動いています．

**Comment by kyouryuukunn** [comment]
dev版にて期待通りの動作を確認しました。対応ありがとうございます。

**Comment by rhysd** [comment]
確認ありがとうございます！
別の箇所でテストが落ちているので，それを直したら master のほうにマージします．
