### ISSUE TITLE
Remap the "t" key to another one ?

### ISSUE THREAD

**Issue by Loelo** [rhysd/clever-f.vim#25]
Hello ! 
Thanks for this smart plugin.  Would there be a simple way to replace "t" by "j" because I use a different keyboardmap ? (bépo which is the french Dvorak sort of. j is already remapped as t in my vimrc and t to j but the plugin overwrite this remapping that is done with nnoremap). 
Thanks and have a good day !

**Comment by rhysd** [comment]
Hi, @Loelo.

You can do it by writing a setting to your `vimrc` as following:

```vim
let g:clever_f_not_overwrites_standard_mappings = 1

map f <Plug>(clever-f-f)
map F <Plug>(clever-f-F)
map T <Plug>(clever-f-T)
map j <Plug>(clever-f-t)
```

At first, set the variable to prevent clever-f from mapping keybinds automatically.  Then you can map them to your favorite keys.  In above, clever-f's `t` will be mapped to `j` and others will be mapped to default keys.

**Comment by Loelo** [comment]
Thanks a lot for your fast answer and the advice : exactly what I was looking for and very simple to do !

**Comment by Loelo** [comment]
Hello, I just noticed : should'nt "T" in the code above be "J" instead ?

**Comment by rhysd** [comment]
Replacing `T` with `J` like below works well:

```vim
map J <Plug>(clever-f-T)
```

You can see the document for `:map` by `:help :map`.

**Comment by Loelo** [comment]
All right, thank you and have a nice day !

**Comment by rhysd** [comment]
:smile:
