### ISSUE TITLE
Enhancement: combine clever-f with shot-f

### ISSUE THREAD

**Issue by sappo** [rhysd/clever-f.vim#29]
I just stumbled acros [deris/vim-shot-f](https://github.com/deris/vim-shot-f) plugin which is a really nice feature for the f,F,t,T keys. But sadly it does not work with clever-f which I like even more :)

Is there a chance to combine them or implement something similar in clever-f? I might be able to do the implementation if I get some pointers.

**Comment by kwinczek** [comment]
Another nice feature is what [kepbod/quick-scope](https://github.com/kepbod/quick-scope) does. Unfortunately they don't work well with clever-f. Any chances of getting them play nicely together or implementing similar functionality in clever-f?

**Comment by yuntan** [comment]
Implemented shot-f like behavior. #47

**Comment by rhysd** [comment]
Closing as #47 was merged.
