### ISSUE TITLE
Dont work when I try to find less-than sign (<)

### ISSUE THREAD

**Issue by BjornMelgaard** [rhysd/clever-f.vim#30]
When I press `f<` or `F<` etc  - less-than sign nor highlighted nor searched, am I one who has such experience? 

Neovim, archlinux

**Comment by rhysd** [comment]
At least in my environment, it works well with neovim. Could you let me know your environment? (neovim version).

And please ensure that clever-f.vim was correctly loaded. For example, `:nmap f` must show the mapping is mapped to `<Plug>(clever-f-...)`. If not, your plugin manager setup maybe failed.

**Comment by rhysd** [comment]
Note: my environment is 

```
NVIM v0.2.0-280-ge21aef1
Build type: RelWithDebInfo
```

on macOS 10.11

**Comment by BjornMelgaard** [comment]
f is mapped correctly, also I have found that f< don't work only in neovim-qt, from terminal it works fine
`vnoremap < <gv` also don't work
I'll close issue, but thanks anyway, :smile:

**Comment by rhysd** [comment]
Thank you for clarifying it.
