### ISSUE TITLE
cursor position not right when `set selection=exclusive`

### ISSUE THREAD

**Issue by ZSaberLv0** [rhysd/clever-f.vim#34]
to reproduce:

1. `set selection=exclusive`
1. assume we have these text (`|` means cursor position)

        |abcdef

1. `v` to enter visual mode
1. press `fc`
    * with clever-f, the result would be (`ab` selected)

            ab|cdef

    * without clever-f, the right result should be (`abc` selected)

            abc|def

**Comment by rhysd** [comment]
Fixed at 6ce2c36. Could you try the latest?

**Comment by ZSaberLv0** [comment]
great work, this did solve the problem
