### ISSUE TITLE
Using f for next search

### ISSUE THREAD

**Issue by kuator** [rhysd/clever-f.vim#45]
Hi, thanks for a great plugin. I have a question. Is there a way to exit f-repeating mode?
Now, to make another search instead of repeating, I'm pressing some random key.
Is it possible to  make some mapping like `map <esc> call  f-repeating-mode-exit()`.
Thanks in advance

**Comment by rhysd** [comment]
> If you want to reset the searching character without moving cursor, map <Plug>(clever-f-reset) to your favorite key.

from [README](https://github.com/rhysd/clever-f.vim/blob/master/README.md)

**Comment by kuator** [comment]
@rhysd thanks
