### ISSUE TITLE
ct/cf combinations change cursor appearance

### ISSUE THREAD

**Issue by marselmustafin** [rhysd/clever-f.vim#51]
Looks like plugin resets some cursor attributes after `ct/cf` combinations, before the change my cursor was horizontal, but after `ct` command it became a block:
![июля-22-2019 16-45-06](https://user-images.githubusercontent.com/19539397/61637462-3f677380-aca0-11e9-9e21-a60ae7d7f94b.gif)
Tried to disable plugin in `.vimrc` and it helped, so I'm sure problem related to the plugin. If there's some hotfix, that I can paste in my `.vimrc` I would appreciate it.

**Comment by rhysd** [comment]
Could you give more information for reproducing this?

1. Which Vim or Neovim are you using?
2. The version of Vim/Neovim
3. The output of `set guicursor` before reproducing this
4. The output of `set guicursor` after reproducing this

**Comment by marselmustafin** [comment]
@rhysd 
1. Neovim
2. 0.3.8
3. guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20,n:hor20-Cursor/lCursor
4. guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20

**Comment by rhysd** [comment]
I'm sorry for the delay. I could not spare time to touch this issue.

And thanks for the clarification. Now I could reproduce this with Neovim v0.3.8 and clever-f.vim 49317cf235bf122d5bbc1c08c3782293904b53cb

**Comment by rhysd** [comment]
I fixed that restoring cursor is not applied on operator-pending mode on neovim at baceb2c. Now cursor shape should not be changed while operator-pending mode `f` and `t`.

**Comment by marselmustafin** [comment]
@rhysd thank you!
