### ISSUE TITLE
Breaks lazyredraw

### ISSUE THREAD

**Issue by Akuseru1** [rhysd/clever-f.vim#57]
when using a macro with lazyredraw **on**, the screen should not redraw, but when using f, F, t and T, the screen will always redraw.

I tested this with a bare neovim config

**Comment by rhysd** [comment]
Please provide steps to reproduce the issue.

**Comment by Akuseru1** [comment]
> Please provide steps to reproduce the issue.

1. Install clever-f in neovim
2. open a file with some text
3. press q and any letter to start a macro
4. use f, F, t or T in the macro
5. press q to save the macro
6. run the macro on any number of lines

**Comment by rhysd** [comment]
I tried following steps but it worked correctly. Can you provide more exact steps and expected/actual behaviors?

1. Install clever-f.vim
2. Open file with some text
3. `set lazyredraw`
4. `qa` to start macro recording
5. `faff` to move cursor to the 3rd 'a'
6. `q` to stop macro recording
7. `0` to move cursor to the head of line
8. `@a` to run the macro
9. Check the cursor moved to the 3rd 'a' again

**Comment by Akuseru1** [comment]
as an example, say you have a file with this line `abc { abc }` repeated 5000 lines, like this
```
abc { abc }
abc { abc }
abc { abc }
.
.
.
abc { abc }
```
if you create a macro for deleting the `{ abc }` part in every line, you would do it like this:

1. `qa` start macro
2. `t{d$0j` delete { abc } and move to the beginning of the next line
3. `q`
4. `99@a`

**Actual Behaviour**
Applying this macro with `set lazyredraw` doesn't work, you can see how the macro is deleting each `{ abc }` in the buffer in real time.

**Expected Behaviour**
Applying this macro with `set lazyredraw` would freeze the buffer until the macro is done. then it should redraw the buffer to see the changes the macro did. 

**vim** 
neovim 0.5.0 nightly

**Comment by rhysd** [comment]
Thank you for the details. Let me try it out.

**Comment by rhysd** [comment]
I could fix the issue at 52e0025. Please update to the latest. Thank you for the details to reproduce the issue.

**Comment by rhysd** [comment]
Note that this issue was only fixed in below versions.

- Neovim 0.4.0 or later
- Vim 8.1.0020 or later
