### ISSUE TITLE
underline target characters without changing its color

### ISSUE THREAD

**Issue by smartding** [rhysd/clever-f.vim#58]
`g:clever_f_mark_char_color` allows me to set highlight group of target characters, but I just want to underline the  target characters while keeping the rest of its original highlight setting.
Is this possible?

**Comment by rhysd** [comment]
```vim
autocmd ColorScheme * highlight default CleverFMyOwnLabel cterm=bold,underline gui=bold,underline
let g:clever_f_mark_char = "CleverFMyOwnLabel"
```

Try this.

**Comment by smartding** [comment]
thanks.
