### ISSUE TITLE
Clear highlights after timeout

### ISSUE THREAD

**Issue by emiham** [rhysd/clever-f.vim#60]
Just found this addon and I really like it! 

One thing that struck me though is that if you set a timeout the highlights remain even after it's triggered. I think it would make sense to clear them once you no longer have the option to jump to them without starting a new search.

**Comment by rhysd** [comment]
> I think it would make sense to clear them once you no longer have the option to jump to them without starting a new search.

Can you show some example? If target character exists in the line, it means cursor can always jump to it. Cursor can go backward with `F` after going forward.

**Comment by rhysd** [comment]
BTW I implemented highlight timeout today. It might be helpful for you.

https://github.com/rhysd/clever-f.vim#highlight-timeout

**Comment by emiham** [comment]
> Can you show some example? If target character exists in the line, it means cursor can always jump to it. Cursor can go backward with `F` after going forward.

I just meant that you can't go there with just `f` (which is the point of the timeout), but you can of course still reach it with a new search. 

Thanks for the incredibly quick fix, it works perfectly!
