### ISSUE TITLE
E523 in nvim_buf_set_lines

### ISSUE THREAD

**Issue by rockyzhang24** [rhysd/clever-f.vim#65]
Have been using `clever-f` for a really long time. Recently, I encounter an error that is shown below

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/11582667/162643195-5eb69ba1-0dcb-4951-b76d-b8666883053f.png">

I am using [fidget.nvim](https://github.com/j-hui/fidget.nvim) to show the progress of LSP. I am not sure whether this issue is caused by `clever-f` or `fidget.nvim`. It seems that this issue is related to https://github.com/neovim/neovim/issues/16278, i.e., the `<expr>` + `getchar()` thing.

This issue happens during the initialization of the LSP servers. After the initialization, no issues. 

Nvim version: NVIM v0.7.0-dev+1429-g8bdcd832a

Thank you very much.

**Comment by rhysd** [comment]
Please describe the reproduction of this issue step-by-step.

**Comment by rockyzhang24** [comment]
Sure. 
1. Use Neovim the latest nightly version
2. Install [fidget.nvim](https://github.com/j-hui/fidget.nvim) and enable it by calling `lua require "fidget".setup {}` in `init.vim`
3. Install `lua` LSP server and enable it via [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#sumneko_lua). For this step, just use `lua` as an example because `lua` LSP server needs longer time for initialization, so it will be easier to reproduce this issue.
4. Install `clever-f`. 
5. Open any `lua` file and then we can see that the progress of the `lua` LSP server initialization is shown on the bottom right corner by `fidget.nvim`.
6. Before the finish of the initialization, press `f` plus any char, then the issue will be appear. 

I believe this issue is related to https://github.com/neovim/neovim/issues/16278, i.e., caused by `<expr>` in the mapping. Based on the comment, I use `<Cmd>` to call the functions instead of using `<expr><Plug>` (shown below), the issue is solved.

```vim
let g:clever_f_not_overwrites_standard_mappings = 1
nmap f <Cmd>call clever_f#find_with('f')<CR>
xmap f <Cmd>call clever_f#find_with('f')<CR>
omap f <Cmd>call clever_f#find_with('f')<CR>
nmap F <Cmd>call clever_f#find_with('F')<CR>
xmap F <Cmd>call clever_f#find_with('F')<CR>
omap F <Cmd>call clever_f#find_with('F')<CR>
nmap t <Cmd>call clever_f#find_with('t')<CR>
xmap t <Cmd>call clever_f#find_with('t')<CR>
omap t <Cmd>call clever_f#find_with('t')<CR>
nmap T <Cmd>call clever_f#find_with('T')<CR>
xmap T <Cmd>call clever_f#find_with('T')<CR>
omap T <Cmd>call clever_f#find_with('T')<CR>
```

Thank you so much.

**Comment by rockyzhang24** [comment]
@wookayin Sure.
