### ISSUE TITLE
Feature Request: Reset highlights when <Esc> key is pressed

### ISSUE THREAD

**Issue by ranelpadon** [rhysd/clever-f.vim#72]
I have this mapping to clear/reset the Vim's **search** results highlights (i.e. when using `/`):
```vim
nnoremap <Esc> :noh<CR>
```

So, I'm thinking if it's possible to use the `<Esc>` key also to reset the `clever-f` highlights instead of using the cursor keys?
> Highlight won't be cleared until the cursor moves. 

I think it's better UX than using `g:clever_f_highlight_timeout_ms` since sometimes you're not done yet, but the highlight will be auto-cleared. Clearing it on-demand offers more timing control. I think `<Esc>` is also a natural choice since it's kinda escaping the `clever-f` (find) mode.

BTW, thanks a lot for this useful/practical plugin! :)

**Comment by rhysd** [comment]
You can do both `:noh` and resetting highlights.

```vim
nnoremap <Esc> :noh<CR>:call clever_f#reset()<CR>
```

**Comment by ranelpadon** [comment]
@rhysd This works! Thanks for the brilliant tip! Will close this issue now. :)
